name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  bootcamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CUDA toolkit setup
        uses: Jimver/cuda-toolkit@v0.2.36

      - name: Build startorch project
        run: |
          cmake -B build
          cmake --build build

      - name: Unit test
        run: |
           ctest --test-dir build 
