name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  bootcamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolkit
        uses: jimmy-wei/cuda-toolkit@v0.2.2
        with:
          cuda-version: '12.4.1'

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Test
        run: |
           ctest --test-dir build 
